---
site_name: SwimChrono Wiki
site_url: https://dfr99.github.io/SwimChrono/
# site_dir: .

repo_url: https://github.com/dfr99/SwimChrono.git
repo_name: dfr99/SwimChrono
edit_uri: ""

theme:
    name: material
    language: en
    font:
        text: Roboto
        code: Roboto Mono
    direction: ltr
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - toc.follow
        - toc.integrate
        - search.highlight
        - search.suggest
        - search.share
        - announce.dismiss
        - git-revision-date:
          enabled_if_env: CI
        - git-revision-date-localized:
          type: date
          fallback_to_build_date: true
          enable_creation_date: true
    icon:
        repo: fontawesome/brands/github
    plugins:
        - tags
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
          primary: indigo
          accent: indigo
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
          primary: indigo
          accent: indigo

markdown_extensions:
    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - toc:
          permalink: true

    # Python Markdown Extensions
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde

nav:
    - Inicio: index.md
    - Contribuciones: contributing/index.md
    - Público Objetivo: target.md
    - Estudio de mercado: market-study.md
    - Documentación técnica:
          - Actores: development/actors.md
          - Arquitectura: development/architecture.md
          - Wireframes:
                - Diseño: development/wireframes.md
                - Implementación: development/wireframes-implementation.md
    - Componentes: components/index.md
    - Integraciones:
       - Bluetooth: integrations/bluetooth.md
       - Almacenamiento: integrations/storage.md
       - Firebase: integrations/firebase.md
    - Guia de Usuario:
          - Primeros pasos: user-guide/getting-started.md
          - Herramientas: user-guide/tools.md
    - Usabilidad y UX: ux/index.md
